import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'User' at '7/4/18 1:29 PM' with Gradle 2.14.1
 *
 * @author User, @date 7/4/18 1:29 PM
 */
public class LibraryTest {
    
}
